name: Release Krayt
on:
  workflow_dispatch:
  push:
    paths:
      - "krayt/**"
      - "pyproject.toml"
permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none
  id-token: write
jobs:
  release-krayt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: waylonwalker/hatch-action@v4
        with:
          before-command: "lint-format"
        env:
          # required for gh release
          GH_TOKEN: ${{ github.token }}
